---
- src: robertdebock.bootstrap
- src: robertdebock.buildtools
- src: robertdebock.epel
- src: robertdebock.scl
- src: robertdebock.python-pip
- src: robertdebock.docker
- src: nephelaiio.git
- src: aeriscloud.nodejs
