---
# Git clone this repo, add/customize inventory files; they will be copied to the target hosts (in main.yml).
- name: Run the AWX installation playbook.
  command: "ansible-playbook -i {{ inventory_file }} install.yml"
  args:
    chdir: "{{ awx_repo_dir }}/installer"
    creates: /etc/awx_playbook_complete

- name: Create a file to mark whether this playbook has completed.
  file:
    path: /etc/awx_playbook_complete
    state: touch
  changed_when: False
