---
- name: Set awx_secret_key
  lineinfile:
    destfile: "{{ awx_repo_dir }}/installer/inventory"
    regexp: '^\s*awx_secret_key=.*$'
    line: "awx_secret_key={{ awx_secret_key }}"
    state: present
  when: awx_secret_key is defined

- name: Set pg_hostname
  lineinfile:
    destfile: "{{ awx_repo_dir }}/installer/inventory"
    regexp: '^\s*#\s*pg_hostname=.*$'
    line: "pg_hostname={{ pg_hostname }}"
    state: present
  when: pg_hostname is defined

- name: Set pg_username
  lineinfile:
    destfile: "{{ awx_repo_dir }}/installer/inventory"
    regexp: '^\s*pg_username=.*$'
    line: "pg_username={{ pg_username }}"
    state: present
  when: pg_username is defined

- name: Set pg_password
  lineinfile:
    destfile: "{{ awx_repo_dir }}/installer/inventory"
    regexp: '^\s*pg_password=.*$'
    line: "pg_password={{ pg_password }}"
    state: present
  when: pg_password is defined

- name: Set pg_database
  lineinfile:
    destfile: "{{ awx_repo_dir }}/installer/inventory"
    regexp: '^\s*pg_database=.*$'
    line: "pg_database={{ pg_database }}"
    state: present
  when: pg_database is defined

- name: Set pg_port
  lineinfile:
    destfile: "{{ awx_repo_dir }}/installer/inventory"
    regexp: '^\s*pg_port=.*$'
    line: "pg_port={{ pg_port }}"
    state: present
  when: pg_port is defined

- name: Set default_admin_user
  lineinfile:
    destfile: "{{ awx_repo_dir }}/installer/inventory"
    regexp: '^#?\s*default_admin_user=.*$'
    line: "default_admin_user={{ default_admin_user }}"
    state: present
  when: default_admin_user is defined

- name: Set default_admin_password
  lineinfile:
    destfile: "{{ awx_repo_dir }}/installer/inventory"
    regexp: '^#?\s*default_admin_password=.*$'
    line: "default_admin_password={{ default_admin_password }}"
    state: present
  when: default_admin_password is defined

# comment out postgres_data_dir
